### ISSUE TITLE
[1.16.4] Dedicated server crashing

### ISSUE THREAD

**Issue by nanonestor** [cech12/CeramicBucket#36]
Hi - Using a 1.16.4 server with Forge 35.0.14 this mod of version ceramicbucket-2.3.1-1.16.2+.jar crashes server.

It happens immediately upon right clicking any entity.

[https://pastebin.com/Ra7aF8Rj](url)

**Comment by cech12** [comment]
Thanks for your report! I will look at this.

**Comment by cech12** [comment]
Thanks for your report! Fixed in 2.3.2

**Comment by nanonestor** [comment]
Thanks!
