### ISSUE TITLE
Missing textures for buckets with liquids 1.16.4

### ISSUE THREAD

**Issue by Blugori** [cech12/CeramicBucket#38]
Hi, I recently installed the 2.3.2 version, and when I tried to fill a bucket, the texture bugged (lava or water).

Forge : 35.0.18
Minecraft : 1.16.4
Ceramic Bucket : 2.3.2
(plus a lot of mods, plus optifine)

Let me know if you need any logs or complementary info :)
Best regards

**Comment by cech12** [comment]
It could be an optifine issue. Please test it without optifine.

**Comment by Blugori** [comment]
I was using the mod "get in the bucket", and was thinking the bug might come from it, I deleted it and everything is fine !
