### ISSUE TITLE
Server crashing inside ItemStack.getDisplayName()

### ISSUE THREAD

**Issue by ClaudiusMinimus** [cech12/CeramicBucket#42]
Minecraft: 1.16.4
Forge: 35.1.12
Ceramic Bucket: 2.5.1-1.16.2

Our server crashed three times yesterday morning. One of the players on my server reported:

>    ok so on the sic server mymo gave me a storage scanner and a pitiful generator...when we tried to use it it crashes the server..3 times. 
on my server it seems to work fine, no crashes. but on mine i only have 10 storage, your server i have 30ish...might be too much communications?

Another player told me he thought the crash happened when the sort button was pressed. I have a few inventory tweak mods in the pack, so I'm looking at that too.

https://pastebin.com/QEjEupZt

Originally, I thought this crash was from RFTools Storage, but as McJty puts it:
> This is actually a bug in cech12.ceramicbucket. They are crashing while trying to get the name of the item. Please report to them. It's crashing inside ItemStack.getDisplayName() for their item

Here is a link to the full issue report I made on the RFTools Storage github
https://github.com/McJtyMods/RFToolsStorage/issues/29

BTW: Here is a link to the pack https://www.curseforge.com/minecraft/modpacks/survival-in-chaos/files/3136503

Thank you,
CM

**Comment by cech12** [comment]
Thanks for your report! Found well! :)

**Comment by cech12** [comment]
Will be released in next version

**Comment by ClaudiusMinimus** [comment]
BTW: I just hit 1,600 downloads for my modpack which uses your mod!
https://www.curseforge.com/minecraft/modpacks/survival-in-chaos

**Comment by cech12** [comment]
released in 2.5.2
