### ISSUE TITLE
Mod support for AlexMobs, Environmental, The Undergarden

### ISSUE THREAD

**Issue by bloche1871** [cech12/CeramicBucket#46]
These mods add bucket fishes and it would be nice to have support for them.
Here are links to them:

https://github.com/Alex-the-666/AlexsMobs
https://github.com/team-abnormals/environmental
https://github.com/quek04/The-Undergarden

**Comment by cech12** [comment]
Additional links and information:
- https://www.curseforge.com/minecraft/mc-mods/alexs-mobs
  - Lobster & Blobfish (see [here](https://github.com/Alex-the-666/AlexsMobs/blob/main/src/main/java/com/github/alexthe666/alexsmobs/item/ItemModFishBucket.java))
- https://www.curseforge.com/minecraft/mc-mods/environmental (error?!)
  - Slabfish & Koi (see [here](https://github.com/team-abnormals/environmental/tree/main/src/main/java/com/minecraftabnormals/environmental/common/entity))
- https://www.curseforge.com/minecraft/mc-mods/the-undergarden
  - ...

**Comment by bloche1871** [comment]
Ah right, Environmental is still in beta, but I think it's supposed to be coming out very soon. It's part of the same TeamAbnormals series of mods as Upgrade Aquatic, which is already supported.

And the Undergarden fish is called "Gwibling" (https://github.com/quek04/The-Undergarden/blob/1.16/src/main/java/quek/undergarden/entity/GwiblingEntity.java)

**Comment by cech12** [comment]
done and will be released in 2.5.4
