### ISSUE TITLE
1.16.5 create chocolate fluid named incorrectly

### ISSUE THREAD

**Issue by imliterallydoingthistoreportabug** [cech12/CeramicBucket#49]
i don't actuall y know if this is an issue with this mod or with create bc all the fluids added from other mods are fine but the chocolate fluid from create shows up as "Ceramic fluid.create.chocolate Bucket" when in a bucket

**Comment by cech12** [comment]
Thanks for your report. It looks like an issue with the create mod. The "fluid.create.chocolate" and "fluid.create.honey" strings are missing in their language files.

**Comment by imliterallydoingthistoreportabug** [comment]
oh thank you for doin that

**Comment by cech12** [comment]
Maybe using Fluid.getAttributes().getTranslationKey() could fix that.

**Comment by cech12** [comment]
fixed
will be released in 2.6.2
