### ISSUE TITLE
item name flavor different from vanilla taste

### ISSUE THREAD

**Issue by MilkissWhite** [cech12/CeramicBucket#5]
while I creating ko-kr language file, I figure out when not using fluid mods, item names are very different from vanilla taste.

 vanilla - 
 bucket
 milk bucket
 bucket of cod
 bucket of salmon
 bucket of tropical fish
 bucket of puffer fish
 water bucket
 lava bucket

 ceramicbucket mod
 ceramic bucket - can edit in language json file
 ceramic bucket (milk) - can edit in language json file
 ceramic bucket (water) (cod)
 ceramic bucket (water) (salmon)
 ceramic bucket (water) (tropical fish)
 ceramic bucket (water) (puffer fish)
 ceramic bucket (water)
 ceramic bucket (lava)

---
 I don't using any fluid mods, so this feel weird little to me.
 fortunally, I can change name of milk bucket by edit language file. I can not change other items even I put some lines.
 I'll upload ko-kr file as new post I made after this post(new issue). I hope other items can be change-able or default item names change to more vanilla taste names.

**Comment by cech12** [comment]
Yes, you are right! Thanks for the hint. I will look what I can do. :)
Maybe I will support both. The default values will be changed to vanilla like names and they will be changeable via language file.

**Comment by cech12** [comment]
Ok I decided to change the item names to more vanilla taste names without the optional change inside the language file. So there are two more entries:

item.ceramicbucket.ceramic_fish_bucket - for all fish buckets. (with a %s you can decide where the fish name should appear)
item.ceramicbucket.filled_ceramic_bucket - for all filled buckets (with a %s you can decide where the fluid name should appear)

I hope this fixes the issue. :)

**Comment by MilkissWhite** [comment]
wow it sounds better than I imagined.

 I worry about just a little point. in korean language, some decorative words call "조사(jo-sa)" will attach to noun.
 for example, Bucket of Salmon in vanilla minecraft. it's korean name is "연어가 든 양동이"
 if I reverse-translate, "연어가 든 양동이" is "Bucket that have Salmon inside". in korean language, almost state will be explain instead using simple "of" like word "의". they use "의" when express some ownership. it's simillar to "~~'s"(example, Mike's book) in english. 

 let's back, "Bucket" is "양동이", "Salmon" is "연어". and "of" will make trouble in the future.
 "jo-sa" will be changed it's shape what kind of noun attached. this case, "jo-sa" is "가".
 "가" will attach to all 대구, 연어, 복어, 열대어(cod, salmon, puffer, tropical fish). so, basically there is no problem now. 
 but if noun have some different text in last part, "가" need to be changed to "이".
 for example, "Sea anemone" is "말미잘", "Black Porgy" is "감성돔". in these case "이" will attach.

 so, I need to decide choice only one. "%s 가 든" or "%s 이 든". now I will choice "%s 가 든" because all fish names in vanilla minecraft is correct with "가". but if minecraft update some object can scoop up bucket, and if it's name is need to attach "이" instead "가", it will be very wierd.

anyway, using %s is very wise choice. easy to cutom. I consent that idea.
I just hope when minecraft update more creatures can scoop up, it's name not conflict this korean language system...

**Comment by cech12** [comment]
That's good to know. Thanks for your description. So, if minecraft will change something, this could be a new issue. :)

**Comment by cech12** [comment]
I have changed your korean language file: https://github.com/cech12/CeramicBucket/issues/6
Is it correct?
