### ISSUE TITLE
korean language file (ko-kr.json)

### ISSUE THREAD

**Issue by MilkissWhite** [cech12/CeramicBucket#6]
little translation. 

[ko_kr.zip](https://github.com/cech12/CeramicBucket/files/4271072/ko_kr.zip)

 I did put some lines like "item.ceramicbucket.ceramic_cod_bucket"(salmon_bucket......etc) but not working(item name still using "item.ceramicbucket.ceramic_bucket" value). only milk bucket name change working.
 so game show me "ceramic bucket of cod" is still "ceramic bucket (water) (cod)", "ceramic milk bucket"(originally "ceramic bucket (milk)") is "ceramic milk bucket".

**Comment by cech12** [comment]
Thabks a lot! When I implemented the name change, I will ask you for an actual file. :D

**Comment by cech12** [comment]
Hey! I update the language file. 

https://github.com/cech12/CeramicBucket/blob/master/src/main/resources/assets/ceramicbucket/lang/en_us.json

Can you please update the korean language file and send it here?

**Comment by cech12** [comment]
Is that file correct?
https://github.com/cech12/CeramicBucket/commit/0a95f02cc2f24858fdc469f5d7b38bdaa5154563

**Comment by MilkissWhite** [comment]
I think this will work well.

[ko_kr.zip](https://github.com/cech12/CeramicBucket/files/4300210/ko_kr.zip)

**Comment by cech12** [comment]
Thanks for your rework. :) I decided to use the file without parenthesis.
