### ISSUE TITLE
custom recipes

### ISSUE THREAD

**Issue by Hyrcas** [cech12/CeramicBucket#68]
### Minecraft Version

1.19.2

### Forge Version

43.2.11

### Mod Version

3.1.0.0

### Describe the Issue

trying to create a custom recipe but i can't seem to refer to specific filled buckets using kubeJS if i say `ceramicbucket:ceramic_bucket` i have no way to specify wich liquid is inside the bucket.

**Comment by cech12** [comment]
Please see here: https://github.com/cech12/CeramicBucket/wiki#usage-in-datapack-recipes

Let me know if this was helpful :)

**Comment by cech12** [comment]
Since Minecraft 1.18 the ingredient types of the BuketLib mod should be used. Here are some example recipes:
https://github.com/cech12/BucketLib/tree/1.19/src/main/resources/data/bucketlib/recipes

**Comment by Hyrcas** [comment]
> Since Minecraft 1.18 the ingredient types of the BuketLib mod should be used. Here are some example recipes: https://github.com/cech12/BucketLib/tree/1.19/src/main/resources/data/bucketlib/recipes

thank you that worked.

if anyone is reading this and has the same question i'll leave here how i did it:

```
{
  "type": "minecraft:crafting_shaped",
  "pattern": [
    "FFF",
    "BEC",
    "FFF"
  ],
  "key": {
    "F": {
      "tag": "forge:cobblestone"
    },
    "B": {
        "type": "bucketlib:fluid",
        "fluid": "minecraft:water"
    },
    "C": {
        "type": "bucketlib:fluid",
        "fluid": "minecraft:lava"
    },
    "E": {
      "tag": "forge:glass"
    }
  },    
  "result": {
    "item": "cobblefordays:tier_2"
  }
}
```

**Comment by cech12** [comment]
I added some information about datapack recipes to the BucketLib wiki: https://github.com/cech12/BucketLib/wiki/Datapack-Recipes

and I added a reference to that page in the Ceramic Bucket wiki: https://github.com/cech12/CeramicBucket/wiki#usage-in-datapack-recipes
