### ISSUE TITLE
[1.19.2 Feature]: Blacklist liquids in a config file

### ISSUE THREAD

**Issue by vizthex123** [cech12/CeramicBucket#72]
### Describe the Feature

There's some fluids that only half-work with the bucket (so far, Cognitium from [Experience Obelisk](https://www.curseforge.com/minecraft/mc-mods/experience-obelisk), so it'd be nice if modpack authors could blacklist them in a config file.

**Comment by cech12** [comment]
Thanks for your report! 

I thought about a possibility to deactivate fluids. But a better way to solve this issue could be to fix the fluid compatibility :)

Which part of the fluid does not work?

**Comment by vizthex123** [comment]
> Thanks for your report!
> 
> I thought about a possibility to deactivate fluids. But a better way to solve this issue could be to fix the fluid compatibility :)
> 
> Which part of the fluid does not work?

you can right-click to deposit it back into the Obelisk, but if you do so with a clay bucket it just places the block.

**Comment by cech12** [comment]
note for me:

Experience Obelisk only supports its own buckets at right click behaviour. So, other mods with other fluid containers doesn't work for now.

master: https://github.com/terrarium-earth/Experience-Obelisk/blob/master/src/main/java/com/cyanogen/experienceobelisk/block/ExperienceObeliskBlock.java#L90

1.19.2: https://github.com/terrarium-earth/Experience-Obelisk/blob/content-expansion-1.19.2/src/main/java/com/cyanogen/experienceobelisk/block/ExperienceFountainBlock.java#L87 (open todo)

When I have time, I will open a PR to support other mods fluid containers.

**Comment by vizthex123** [comment]
noice.

**Comment by cech12** [comment]
I opened a PR for Experience Obelisk: https://github.com/terrarium-earth/Experience-Obelisk/pull/16

**Comment by cech12** [comment]
@vizthex123 The Experience Obelisk is supported since experienceobelisk-v1.4.10 (1.20.1, 1.19.2, 1.18.2)

There is another issue https://github.com/cech12/BucketLib/issues/11 where the topic is continued. If you have any other fluids or mods that are having issues, please feel free to open an issue here at Github. :)

**Comment by vizthex123** [comment]
> @vizthex123 The Experience Obelisk is supported since experienceobelisk-v1.4.10 (1.20.1, 1.19.2, 1.18.2)
> 
> There is another issue [cech12/BucketLib#11](https://github.com/cech12/BucketLib/issues/11) where the topic is continued. If you have any other fluids or mods that are having issues, please feel free to open an issue here at Github. :)

noice, thanks.
