### ISSUE TITLE
[Bug]: Naming of milk bucket messed up.

### ISSUE THREAD

**Issue by ryanc16** [cech12/CeramicBucket#74]
### Minecraft Version

1.20.1

### Forge Version

47.2.0

### Mod Version

4.1.0.0

### Describe the Issue

The name of the Ceramic Milk Bucket is messed up, instead reading "Ceramic fluid.minecraft.milk Bucket". See attached image.
![image](https://github.com/cech12/CeramicBucket/assets/11671601/9e610986-edf2-4050-8676-e044bdae5a77)

**Comment by cech12** [comment]
Thanks for your report! I will look into this :)

**Comment by cech12** [comment]
Another question: You have a bucket with the pink and black pixels (the last ceramic bucket before powder snow in the screenshot) What is the content of this bucket?

**Comment by ryanc16** [comment]
Sure thing. I checked and it says its "Ceramic Bucket of Spinefish". Spinefish being from the Aquamirae mod. Not sure how you handle other mods that add new bucket items. That could be a whole other issue in itself I'm sure.
![image](https://github.com/cech12/CeramicBucket/assets/11671601/33bd9652-ad4e-47ef-99d3-066c628faf92)

**Comment by cech12** [comment]
Thanks for your response. Yes, this is another issue, which can be fixed easily by adding a texture to the right position^^
I will fix that, too :)

**Comment by ryanc16** [comment]
Thank you so much for your time!

**Comment by cech12** [comment]
A fix for both issues (milk translation & missing texture) will be released in BucketLib 1.19.2-1.0.7.0, 1.19.4-1.3.0.2, 1.20.1-2.3.0.2 and 1.20.2-2.4.0.2 soon.
