### ISSUE TITLE
[Feature]: Allow buckets to hold less than 1000 mb.

### ISSUE THREAD

**Issue by CraftyZombie** [cech12/CeramicBucket#75]
### Describe the Feature

If a bucket could hold less than 1000 mb of a fluid at once, it would make interacting with modded fluid storage blocks much easier.

**Comment by CraftyZombie** [comment]
Also, if you were to implement this, would you consider supporting 1.20.1 still, or are you only doing 1.20.2 now?

**Comment by cech12** [comment]
The target of this mod is to add a bucket with the same interactions like a vanilla bucket.

There are multiple questions which come up if a bucket has less than 1000 mb:
- How do you empty/clear such a bucket? Is the content still placeable? (Infinite fluid) 
- How do you refill it? With a full fluid source? (fluid loss) 
- what happens with a cracked bucket? Is the fluid lost after one interaction or could you interact multiple times with a cracked bucket? 
- ... 

I think these questions cannot be answered in a user-friendly and easy-to-use way without giving the possibility to generate infinite fluid or loose fluid.

Actually I am working on a 1.20.2/1.20.4 version for Forge and NeoForge. So, the support for 1.20.1 will be dropped soon.

**Comment by CraftyZombie** [comment]
Yeah, those are all good questions.

1. Contents would not be placeable. Only moved into another fluid container.
2. You'd need to refill it using a fluid container, not a source block.
3. I'd imagine that the bucket would crack after one interaction anyway, as a very hot fluid would break open the bottom of the bucket and it'd be unusable regardless.

I understand why you wouldn't want to add that all though, it probably overcomplicates things in retrospect.

**Comment by cech12** [comment]
Thanks for your input :) Yes, that would overcomplicate everything. So, I would not add this feature :)
