### ISSUE TITLE
[Bug]: The lava bucket does not serve as fuel in the furnace or blast furnace.

### ISSUE THREAD

**Issue by memoharos** [cech12/CeramicBucket#83]
### Minecraft Version

1.21

### Mod Loader

Fabric

### Mod Loader Version

0.16.5

### Mod Version

6.1.1

### Describe the Issue

The lava bucket does not serve as fuel in the furnace or blast furnace.

**Comment by cech12** [comment]
Thanks for your report. That should be a BucketLib issue. https://github.com/cech12/BucketLib/issues/49

I will look into that when I have time.

**Comment by cech12** [comment]
@memoharos Fixed in upcoming BucketLib versions 1.21-4.1.0.4, 1.20.6-3.3.0.11 and 1.20.4-3.2.1.6. Thanks again for your report!
